### ISSUE TITLE
Sidebar Menu Font

### ISSUE THREAD

**Issue by tblake84** [ff36/halo-core#47]
Sidebar menu fails to load.

Code inspected and found:
`downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://10.10.203.254/bower_components/bootstrap/fonts/glyphicons-halflings-regular.woff2`

**Comment by tarkal** [comment]
This is GUI related issue. Can you report it at the GUI repo [https://github.com/ff36/halo-gui](https://github.com/ff36/halo-gui).

However, this shouldn't be responsible for the sidebar not being displayed. 99.9% of the time the sidebar not displaying is a result of specifying an incorrect common name during the GUI install and setup. You can use the **`hadmin`** tool to change it. It must be the same as the IP or common name that you are using to access to system.

e.g. If halo is installed on your network and you are accessing it at `192.168.1.1` then you need to set the IP `hadmin -a=192.168.1.1` or if you are accessing the system using an internal DNS (e.g. some.internal.record) then set that `hadmin -a=some.internal.record`.

**Comment by tblake84** [comment]
Thanks.  Closing issue and will reopen in GUI repo if unresolved.
