### ISSUE TITLE
Multiple sectors can be created for the same hardware

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#48]
If I have a Solid R5 at address (50.50.50.50:20000) I can create multiple sectors using that IP without issue.

**Comment by tarkal** [comment]
This needs to take the full proxied socket into consideration given that the same socket could be used for genuinely different pieces of hardware.

**Comment by tarkal** [comment]
After considerable investigation we have concluded that it should be possible to register multiple versions of the same instance. Some plugins have been designed specifically to allow multiple instances to be registered. 

The system prevents non async requests for hardware that does not support async so this should be sufficient. I am closing this issue for now. If you feel strongly that this does not meet your expectations then please open another issue stating the reasons.
