### ISSUE TITLE
APIMatic breaks timeouts

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#62]
When trying to make a Halo HTTP request to an IP address that isn't running a Halo server the connection never times out; it loops indefinitely until the process is killed.  After speaking with Tarka it would appear that APIMatic has broken the timeout rules defined in the SDK itself.

**Comment by tarkal** [comment]
This belongs in the SDK repo. Please can you re-file it there: https://github.com/ff36/halo-sdk/issues

**Comment by ActionCactus** [comment]
Will do.
