### ISSUE TITLE
Property values have unknown characters in R6 extension

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#63]
In the latest R6 extension available the Optic Serial Number property for an ROU has unknown characters in its value.  These unknown characters show up as question marks when returned by the API.

![image](https://cloud.githubusercontent.com/assets/17009372/14494432/dfd678da-0158-11e6-8aa8-0e2e987aa49f.png)

**Comment by tarkal** [comment]
Thanks. This is actually a problem with the specific R6 plugin. I will duplicate it to the SOLiD R6 repo.
