### ISSUE TITLE
Syntax errors in SettingFieldTypeEnum.php

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#64]
As shown below, using LIST as a constant in PHP is forbidden (sorry, guys, PHP is weird).  Reference the attached article.

http://php.net/manual/en/reserved.keywords.php

![image](https://cloud.githubusercontent.com/assets/17009372/14494504/24396280-0159-11e6-9e5a-f2990f163e7b.png)

**Comment by tarkal** [comment]
This is a valid point for APIMatic. Again please can you file this in the SDK repo.

Although this does not fix the problem, `SettingFieldTypeEnum` should not exist in the latest SDK! Can you check that the latest version you have does not have it.

**Comment by ActionCactus** [comment]
Yep, it doesn't exist in the latest version.

**Comment by tarkal** [comment]
Great. Im closing this here and will get the APIMatic guys to look at it.
