### ISSUE TITLE
"Null" values reported in place of band info in properties

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#68]
In the R5 plugin properties have band names appended to the beginning of the property name followed by a " : " and the property name itself.  In recent additions of the R5 we're seeing "Null : " values being thrown in place of the band name, seemingly for properties associated with the node specifically instead of a band.  

I would take a screenshot, but a memory leak was crashing my server every 30 minutes and after removing /opt/halo/app and running an update I can't seem to upload plugins due to "cannot upload plugins of this file type" errors.

File here because I do not have a log of where the R5 repository is; sorry about that.

**Comment by tarkal** [comment]
@ActionCactus I have moved this to the R5 repo and will report back as soon as we have an update.
