### ISSUE TITLE
Screen display problem with long names

### ISSUE THREAD

**Issue by er144254** [ff36/halo-core#72]
Below is a screenshot of the User screen.  You will notice that for Nicholas, his email extends beyond the confines of the box that represents his user.

<img width="1680" alt="screen shot 2016-04-28 at 10 42 12 am" src="https://cloud.githubusercontent.com/assets/7861000/14894287/18f04b9a-0d30-11e6-8459-f6efee331857.png">

**Comment by tarkal** [comment]
This is a GUI issue and has been moved to the GUI repo:
https://github.com/ff36/halo-gui/issues/211
