### ISSUE TITLE
Personal data

### ISSUE THREAD

**Issue by er144254** [ff36/halo-core#73]
I was logged in as an administrator, but went to switch to another user (using sudo) in order to change his password.  It logged me into the new users account just fine.  However, I was told that upon switching between user I could click on his name in the top left side to access his personal data and change his password.  The mouse icon recognises you can click there, but there seems to be no functionality there.  Nothing happen.

**Comment by tarkal** [comment]
This belongs in the GUI repo. Moving to https://github.com/ff36/halo-gui/issues/203
