### ISSUE TITLE
Username in the first box to of the login screen should be email

### ISSUE THREAD

**Issue by er144254** [ff36/halo-core#74]
On the login page the first box is labeled "Username".  However when setting up the user, you create a username and an email.  This first box is actually requesting the email, not the username.  Please make this consistent.

**Comment by tarkal** [comment]
Currently the system only supports email authentication (it also supports token, and key pairs but these are not relevant to this issue). The system should optionally be able to use the username or the email during the GUI authentication.

Until the core supports username authentication the GUI login field should change the input watermark to say 'Email'.
