### ISSUE TITLE
R5 Extension - inventory changes aren't detected

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#76]
If I have a device inventory Biu > Odu > Dou > Rou and I turn something off (let's say I physically unplug the Odu) Halo doesn't appear to detect these changes, even when I delete the existing sector and then re-add it.  As far as I can tell an incident isn't raised, either.

**Comment by tarkal** [comment]
This could be related to #71. @ActionCactus can you upload your logs please so I can take a look.

**Comment by ActionCactus** [comment]
[Halo Logs.zip](https://github.com/ff36/halo-core/files/242929/Halo.Logs.zip)

**Comment by tarkal** [comment]
The problem with removing nodes without uninstalling is its very difficult to tell the difference between a node being removed and say a bust optical cable. To prevent node ids from changing during rebuild a security manager has been implemented. It will only alter the network structure after an evaluation period when the system is satisfied that the change is deliberate and intended.
