### ISSUE TITLE
R5 Extension - cause, impact, and remedy aren't properly listed

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#82]
Being filed here because I can't find the R5 extension under 555's page; sorry.

Incident cause, impact, and remedy often just have "cause", "impact", or "remedy" as their data (example:  "Cause:  cause").  This is bloat for the user.

**Comment by tarkal** [comment]
Ive moved this to the SOLiD R5 repo: https://github.com/solid-software/r6-halo-desc/issues/2 and SOLiD R6 repo: https://github.com/solid-software/r5-halo-desc/issues/2

@jimwitkin this one is for you...

**Comment by jimwitkin** [comment]
Tarka, apologies, I've lost track. Did you need me to do something with this item?

**Comment by tarkal** [comment]
no
