### ISSUE TITLE
Irregular throttling / failures with paginated requests

### ISSUE THREAD

**Issue by ActionCactus** [ff36/halo-core#84]
We are using the following code to fetch properties from Halo 

![image](https://cloud.githubusercontent.com/assets/17009372/15047762/64e88790-12b4-11e6-85ad-224f542972f5.png)

This code executes for each node underneath any given sector so that all properties are retrieved.

Usually this works just fine, but when run against a particular server in Ohio, USA, we are experiencing irregular timeouts/throttling.  Shown below:

![image](https://cloud.githubusercontent.com/assets/17009372/15047905/05898b5e-12b5-11e6-89ef-946b465156e9.png)

As you can see, this often works as intended, but occasionally it takes drastically longer to execute.  Sometimes the entire application just crashes:

![image](https://cloud.githubusercontent.com/assets/17009372/15048015/82f9fe3e-12b5-11e6-9ab3-ef9934be4741.png)

For the above image, we simultaneously verified modem connectivity while our code execution was in progress, and connectivity never dropped, as shown below:

![image](https://cloud.githubusercontent.com/assets/17009372/15047959/3e2efc6e-12b5-11e6-9dc7-3e65871daf55.png)

**Comment by tarkal** [comment]
This cannot be completely eliminated but has been significantly improved in 1.3.0. I am closing this issue based on a 98% improvement. If you feel this is insufficient for your requirements feel free to re-open another issue.
