### ISSUE TITLE
Networks Tab - Name of the system needs to remain

### ISSUE THREAD

**Issue by er144254** [ff36/halo-core#86]
After doing the float over to select a system and drilling down to the element you want to see.  When you right click to "View Properties" the name of the system disappears.  It would be nice to see the drill down path including the system selected to remaining on the screen.

Additionally, after drilling down to the element level and selecting "View Properties", there is no clean way to go back.  You can't select the icon for Networks or hit the back button.  And with the name gone, you can't click that either.  I would be nice to be able to go back to the beginning of the Network circles.

**Comment by tarkal** [comment]
I agree that the breadcrumb issue. This has already been raised here: https://github.com/ff36/halo-gui/issues/226

Clicking in the center of the network dial goes up a level.
