### ISSUE TITLE
Network Overview

### ISSUE THREAD

**Issue by er144254** [ff36/halo-core#87]
When going into Network Overview, I see the MDBU's as an orange color, indicating degrading service.  However when I "view properties". All of the properties show as green.  When you go look at the sectors and look at the view properties, you can see that the MDBU is orange, then select properties and it shows yellow items.  
[Orange MDBU.pdf](https://github.com/ff36/halo-core/files/284930/Orange.MDBU.pdf)

**Comment by tarkal** [comment]
https://github.com/ff36/halo-gui/issues/262
