### ISSUE TITLE
Screen Lock

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-core#88]
When I opened this Property Information box for one of the MDBUs, I was not able to close it and return to Sectors / R6 (CO) / Nodes view. I had to close the browser tab and restart Halo. 

![image](https://cloud.githubusercontent.com/assets/18722397/16135834/12feee9a-33db-11e6-9abe-71a16a1c149e.png)

**Comment by tarkal** [comment]
This is a GUI problem. Moved repo: https://github.com/ff36/halo-gui/issues/298
