### ISSUE TITLE
An engine object is 'null' 

### ISSUE THREAD

**Issue by sweety-wo** [ff36/halo-core#91]
An engine object is 'null' for 'guiltySector' object in get incident API response
(GET :http://localhost:8080/api/incidents/73%3A2?)

![incident_engine](https://cloud.githubusercontent.com/assets/14175105/16615671/f2562832-4395-11e6-9664-ab1822a37d6e.png)

**Comment by tarkal** [comment]
Fixed in 'remove-hazelcast' branch. I will merge this branch into `1.3.0` in the next hour.

**Comment by tarkal** [comment]
Fixed in 1.3.0
