### ISSUE TITLE
Grammar problems on the delete message

### ISSUE THREAD

**Issue by er144254** [ff36/halo-core#96]
I logged into a Halo instance today and notice and message for the Admin.  I looked at the message and deleted it when I was done.  There is some spacing and duplicate word issues.  
[Deleted message.pdf](https://github.com/ff36/halo-core/files/420844/Deleted.message.pdf)

**Comment by tarkal** [comment]
Moved to correct repo: https://github.com/ff36/halo-gui/issues/431
